### ISSUE TITLE
No devices found on raspberry pi

### ISSUE THREAD

**Issue by virtuosonic** [Agamnentzar/bluetooth-serial-port#10]
Hi, I got your code to compile on raspbian but I only get this output with the  test
`pi@raspberrypi:~/bluetooth-serial-port $ ./inquiretest 

done, found 0 device(s)`

using hcitool I get this:

`pi@raspberrypi:~/bluetooth-serial-port $ sudo hcitool lescanLE Scan ...
4A:A1:54:5B:D0:8E (unknown)
4A:A1:54:5B:D0:8E (unknown)
78:A5:04:16:9E:68 (unknown)
78:A5:04:16:9E:68 Kevo
`

My distro version is:
Raspbian GNU/Linux 9 (stretch)
Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

and gcc version:
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/6/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 6.3.0-18+rpi1+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1+deb9u1)

**Comment by Agamnentzar** [comment]
I think you're searching for Bluetooth low energy devices, it seems to search for them you need to do some extra steps: https://stackoverflow.com/questions/38267072/raspberry-pi-3-ble-scanning Currently this library does not support that. I don't have any way to test BLE devices on linux, but if you want to look into it or just modify the code and use it directly in your project, you'd have to modify code here: https://github.com/Agamnentzar/bluetooth-serial-port/blob/master/src/linux/DeviceINQ.cc#L43
