### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by EchoHowardLam** [Agamnentzar/bluetooth-serial-port#17]
In README.md, it is
```
BTSerialPortBinding::IsDataAvailable(buffer, length)
```

In BTSerialPortBinding.h, it is
```
bool IsDataAvailable();
```

**Comment by Agamnentzar** [comment]
Oops, sorry, it was copy paste error, fixed in 63eeadf7e7dbbe16a8c7876a557f2dd0c4f18a92
