### ISSUE TITLE
Monitoring disconecting

### ISSUE THREAD

**Issue by kubszcz** [Agamnentzar/bluetooth-serial-port#19]
Hi I have a qustion, how is there a function to check whether connection is still alive and device didnt disconect? (Windows)

**Comment by Agamnentzar** [comment]
You should get error while reading `Error reading from connection` or error while writing `Writing attempt was unsuccessful` If you need to check connection without reading or writing you'd probably have to add your own function that just calls `select` like here: https://github.com/Agamnentzar/bluetooth-serial-port/blob/master/src/windows/BTSerialPortBinding.cc#L129 without calling recv after

**Comment by kubszcz** [comment]
Ok, got it, working, thanks!
