### ISSUE TITLE
if connect bluetooth device need password,how can i deal with it?

### ISSUE THREAD

**Issue by jcyhcs** [Agamnentzar/bluetooth-serial-port#20]
hi,professor:
like the topic said
please help!

**Comment by Agamnentzar** [comment]
I think you need to pair your device with your PC and at that point either device or PC will prompt you for password. I don't remember now how that worked.

**Comment by jcyhcs** [comment]
thanks for your answer! i just test your inquire demo code for send data 
enviroment : a embedded borad, a bluetooth device
i find can send data without paired, just call Inquire => BTSerialPortBinding::Create => Connect => Write , is ok.
but i have a question that when have more than two bluetooth devices , my embedded borad want to send data to special one,what can i do? 
your code didn't have pair code!
i think i should record the special bluetooth device's BD_ADDR, then Inquire and compare to find the right one, is this method ok? 
is there a more elegant method?
please help me!

**Comment by Agamnentzar** [comment]
You can check `address` or `name` of the device to check which one it is, you can see all the fields of each device here: https://github.com/Agamnentzar/bluetooth-serial-port#deviceinqinquire
