### ISSUE TITLE
can not connect to any device!

### ISSUE THREAD

**Issue by peyyman** [Agamnentzar/bluetooth-serial-port#6]
Hi,
It seems that DeviceINQ::SdpSearch() always fails (it returns -1 for all devices) . 
I just ran test/main.cpp code and it lists all devices but with -1 for channels. So when I can't create a BTSerialPortBinding, because it needs positive channel id. 

I have tested this on windows 7, VS 2015.

**Comment by Agamnentzar** [comment]
I'm just always passing `1` as channel ID, without using `SdpSearch` and it works ok for me. Not sure what's the issue with `SdpSearch`.
```c++
BluetoothConnection connection(bluetoothDevice.address, 1);
```

**Comment by incebellipipo** [comment]
Its not creating `/dev/rfcommX`

**Comment by atomheartother** [comment]
@Agamnentzar I also encountered this issue and was stuck on it quite a bit before reading this thread. At this point, wouldn't it be better just to document that SdpSearch is useless on windows, and to use 1 instead?

**Comment by Agamnentzar** [comment]
@atomheartother sorry for that, I never understood SdpSearch thing :P I added notes to Readme, with explanation.
